on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: |
          pip install -U requests beautifulsoup4
      - name: Run tests
        run: |
          code/tests.py
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: JQ Json Lint
        run: jq . robots.json
